# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Compulogy
#email: paul.duplys At posteo.de
description: > # this means to ignore newlines until "baseurl:"
  Feedback & comments regarding the posts are welcome - drop me a line to paul dot duplys at posteo dot de! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.duplys.github.io" # the base hostname & protocol for your site
twitter_username: duplys
github_username:  duplys

# Build settings
markdown: kramdown
